// row in config, when to show, name, description
HOTKEY(0, HKV_WINDOW_MODE, alwaysOnTop, ID_OPTIONS_ALWAYSONTOP, "Toggle 'always on top'")
HOTKEY(0, HKV_WINDOW_MODE, cheats, ID_OPTIONS_CHEATS, "Open cheats")
HOTKEY(0, HKV_WINDOW_MODE | HKV_ROM_BROWSER, openROM, ID_FILE_OPEN_ROM, "Open ROM")
HOTKEY(0, HKV_WINDOW_MODE | HKV_ROM_BROWSER, settings, ID_OPTIONS_SETTINGS, "Open settings")
HOTKEY(0, HKV_ROM_BROWSER, startEmulation, ID_FILE_STARTEMULATION, "Start emulation")
HOTKEY(0, HKV_ROM_BROWSER, refreshROMList, ID_FILE_REFRESHROMLIST, "Refresh ROM list")
HOTKEY(0, HKV_CPU_RUNNING, fullScreen, ID_OPTIONS_FULLSCREEN, "Go to fullscreen")
HOTKEY(0, HKV_CPU_RUNNING, cpuReset, ID_CPU_RESET, "Soft reset")
HOTKEY(0, HKV_CPU_RUNNING, endEmulation, ID_FILE_ENDEMULATION, "End emulation")
HOTKEY(0, HKV_CPU_RUNNING, cpuPause, ID_CPU_PAUSE, "Pause emulation")
HOTKEY(0, HKV_CPU_RUNNING, generateBitMap, ID_SYSTEM_GENERATEBITMAP, "Take screenshot")
HOTKEY(0, HKV_CPU_RUNNING, limitFPS, ID_SYSTEM_LIMITFPS, "Limit FPS")
HOTKEY(0, HKV_CPU_RUNNING, gsButton, ID_SYSTEM_GSBUTTON, "GS Button")
HOTKEY(0, HKV_CPU_RUNNING, currentSave, ID_CURRENTSAVE_DEFAULT, "Set savestate default")

HOTKEY(1, HKV_CPU_RUNNING, currentSave0, ID_CURRENTSAVE_0, "Set savestate 0")
HOTKEY(1, HKV_CPU_RUNNING, currentSave1, ID_CURRENTSAVE_1, "Set savestate 1")
HOTKEY(1, HKV_CPU_RUNNING, currentSave2, ID_CURRENTSAVE_2, "Set savestate 2")
HOTKEY(1, HKV_CPU_RUNNING, currentSave3, ID_CURRENTSAVE_3, "Set savestate 3")
HOTKEY(1, HKV_CPU_RUNNING, currentSave4, ID_CURRENTSAVE_4, "Set savestate 4")
HOTKEY(1, HKV_CPU_RUNNING, currentSave5, ID_CURRENTSAVE_5, "Set savestate 5")
HOTKEY(1, HKV_CPU_RUNNING, currentSave6, ID_CURRENTSAVE_6, "Set savestate 6")
HOTKEY(1, HKV_CPU_RUNNING, currentSave7, ID_CURRENTSAVE_7, "Set savestate 7")
HOTKEY(1, HKV_CPU_RUNNING, currentSave8, ID_CURRENTSAVE_8, "Set savestate 8")
HOTKEY(1, HKV_CPU_RUNNING, currentSave9, ID_CURRENTSAVE_9, "Set savestate 9")
HOTKEY(1, HKV_WINDOW_MODE, saveAs, ID_CPU_SAVEAS, "Save savestate to file")
HOTKEY(1, HKV_WINDOW_MODE, cpuLoad, ID_CPU_LOAD, "Load savestate from file")
HOTKEY(1, HKV_CPU_RUNNING, cpuSave, ID_CPU_SAVE, "Save savestate")
HOTKEY(1, HKV_CPU_RUNNING, cpuRestore, ID_CPU_RESTORE, "Load savestate")