CONFIG(fastStates, "Do not reinitialize emu on state load")
CONFIG(fastResets, "Do not reinitialize emu on soft reset")
CONFIG(fixSlowResets, "Fix slow resets")
CONFIG(noLoadSlowdown, "Remove sleeps on ROM open")
CONFIG(cf1ByDefault, "CF1 by default")
CONFIG(useFastDecompression, "Use fast ZIP decompression")
CONFIG(cacheLastSavestate, "Cache last loaded savestate")
CONFIG(fixLoadStateStutter, "Fix stutter on savestate load")
CONFIG(overrideHotKeys, "Override shortcuts")
CONFIG(fixTEQCrash, "Fix recompiler TEQ crashes")
CONFIG(removeCICChipWarning, "Remove CIC Chip errors")
CONFIG(overclockVI, "Overclock VI")