HOTKEY(alwaysOnTop, "Toggle 'always on top'")
HOTKEY(cheats, "Open cheats")
HOTKEY(openROM, "Open ROM")
HOTKEY(cpuLoad, "Load savestate from file")
HOTKEY(saveAs, "Save savestate to file")
HOTKEY(settings, "Open settings")
HOTKEY(startEmulation, "Start emulation")
HOTKEY(refreshROMList, "Refresh ROM list")
HOTKEY(currentSave0, "Set savestate 0")
HOTKEY(currentSave1, "Set savestate 1")
HOTKEY(currentSave2, "Set savestate 2")
HOTKEY(currentSave3, "Set savestate 3")
HOTKEY(currentSave4, "Set savestate 4")
HOTKEY(currentSave5, "Set savestate 5")
HOTKEY(currentSave6, "Set savestate 6")
HOTKEY(currentSave7, "Set savestate 7")
HOTKEY(currentSave8, "Set savestate 8")
HOTKEY(currentSave9, "Set savestate 9")
HOTKEY(fullScreen, "Go to fullscreen")
HOTKEY(cpuReset, "Soft reset")
HOTKEY(endEmulation, "End emulation")
HOTKEY(cpuPause, "Pause emulation")
HOTKEY(generateBitMap, "Take screenshot")
HOTKEY(limitFPS, "Limit FPS")
HOTKEY(cpuSave, "Save savestate")
HOTKEY(cpuRestore, "Load savestate")
HOTKEY(gsButton, "GS Button")
HOTKEY(cpuPause, "Pause emulation")
