HOTKEY(0, alwaysOnTop, "Toggle 'always on top'")
HOTKEY(0, cheats, "Open cheats")
HOTKEY(0, openROM, "Open ROM")
HOTKEY(0, settings, "Open settings")
HOTKEY(0, startEmulation, "Start emulation")
HOTKEY(0, refreshROMList, "Refresh ROM list")
HOTKEY(0, currentSave, "Set savestate current")
HOTKEY(0, fullScreen, "Go to fullscreen")
HOTKEY(0, cpuReset, "Soft reset")
HOTKEY(0, endEmulation, "End emulation")
HOTKEY(0, cpuPause, "Pause emulation")
HOTKEY(0, generateBitMap, "Take screenshot")
HOTKEY(0, limitFPS, "Limit FPS")
HOTKEY(0, gsButton, "GS Button")

HOTKEY(1, currentSave0, "Set savestate 0")
HOTKEY(1, currentSave1, "Set savestate 1")
HOTKEY(1, currentSave2, "Set savestate 2")
HOTKEY(1, currentSave3, "Set savestate 3")
HOTKEY(1, currentSave4, "Set savestate 4")
HOTKEY(1, currentSave5, "Set savestate 5")
HOTKEY(1, currentSave6, "Set savestate 6")
HOTKEY(1, currentSave7, "Set savestate 7")
HOTKEY(1, currentSave8, "Set savestate 8")
HOTKEY(1, currentSave9, "Set savestate 9")
HOTKEY(1, saveAs, "Save savestate to file")
HOTKEY(1, cpuLoad, "Load savestate from file")
HOTKEY(1, cpuSave, "Save savestate")
HOTKEY(1, cpuRestore, "Load savestate")